import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

const prompt = Prompt({
  subsets: ["thai","latin"],
  weight: ["100", "200", "300","400","500","600","600","700","800","900"],
});

export const metadata: Metadata = {
  title: "Food Tracker App",
  description: "Generated by Jirawad SAU",
  keywords: ["Food", "Tracker","อาหาร","สุขภาพ"],
  icons: {
    icon: "/vercal.svg"
  },
  authors: [{
    name: "Jirawad SAU",
    url: "https://jirawadsau.com"
  }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt} ${prompt} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
